# Generated by Django 4.1.3 on 2023-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='PV',
            field=models.FloatField(max_length=9),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='price',
            field=models.FloatField(max_length=9),
        ),
    ]
